/*
 * Copyright Amazon.com, Inc. or its affiliates.
 * All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific
 * language governing permissions and limitations under the License
 */
package com.carddemo.repository;

import jakarta.persistence.EntityExistsException;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import java.sql.SQLException;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Deque;
import java.util.IdentityHashMap;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.orm.jpa.SharedEntityManagerCreator;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.NoTransactionException;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.interceptor.TransactionAspectSupport;

/**
 * The module's write-point primitives: an insert that is an insert, and a flush that happens where the
 * legacy verb happens.
 *
 * <h2>Why a create needs its own verb</h2>
 *
 * <p>Every record in this estate carries a natural business key that the program assigns before the write
 * - an eleven-digit account identifier, a sixteen-character card number or transaction identifier, an
 * eight-character user identifier. None is generated by the store, so a freshly built entity never has a
 * {@code null} identifier, and that is what decides how a repository's {@code save} behaves: Spring Data
 * asks the entity whether it is new, the answer for an assigned non-{@code null} key without a version
 * attribute is <em>no</em>, and {@code save} therefore resolves to a merge. A merge whose row already
 * exists loads that row and updates it.
 *
 * <p>The consequence is precise and severe. Every legacy {@code WRITE} in the estate is a create whose
 * duplicate-key response the program handles explicitly: the transaction-add member reports
 * {@code Tran ID already exist...}, the bill-payment member reports the same, the user-add member reports
 * {@code User ID already exist...}, and the batch posting member abends. Routed through a merge, none of
 * those arms is reachable, and a duplicate key silently becomes a last-write-wins overwrite of somebody
 * else's record. {@link #insert(Object)} and {@link #insertIndependently(Object)} issue a real insert, so
 * a duplicate key is refused by the store and the arm the legacy specifies is the arm that runs.
 *
 * <h2>Why a flush belongs at the write point</h2>
 *
 * <p>A repository {@code save} enqueues work; the statement reaches the database when the persistence
 * context is flushed, which by default is at commit. A {@code catch} around the save therefore never sees
 * the failure it was written to handle - the failure arrives after the method, after its caller and after
 * every screen the turn composed, at a point where no legacy arm exists to receive it. Flushing inside the
 * write primitive puts the failure back where the legacy verb put it, which is the only place the legacy's
 * own response arms can act on it.
 *
 * <h2>The two propagations, and why the choice is not stylistic</h2>
 *
 * <p>{@link #insert(Object)}, {@link #insertAll(Collection)} and {@link #flush()} require the caller's
 * unit of work and join it. That is right for the batch tier: a legacy batch program abends on a failed
 * write and the step is re-run from its last commit point, so a record's writes must succeed or fail
 * together with the record's own boundary. Committing a posted transaction independently of the chunk that
 * produced it would post it twice on the next restart.
 *
 * <p>{@link #insertIndependently(Object)} opens its own unit of work. That is right for the online tier,
 * and for a reason the resource definitions state rather than a convenience: every application file in
 * {@code app/csd/CARDDEMO.CSD} is defined {@code RECOVERY(NONE)} with {@code JOURNAL(NO)}, so a legacy
 * record write is immediately durable and no unit of work backs it out. An online member that reports a
 * failed write on the screen and carries on - which is what the bill-payment member does at its line 233,
 * where the account rewrite at line 235 is reached whether or not the write succeeded - cannot be
 * reproduced inside a single unit of work, because a failed flush leaves that unit unusable for anything
 * that follows. An independent boundary reproduces both halves: the write is durable on its own, and its
 * failure is contained.
 *
 * <p><strong>Independent boundaries are offered for creates only, deliberately.</strong> An update reads
 * its row first, and that row is then managed by the reading unit of work. Writing it through a second,
 * independent unit of work would leave the first one still holding a dirty copy, which it would write
 * again at its own commit - a second update carrying a stale version. Updates therefore stay in the
 * caller's unit of work and flush there, through the repository's own {@code saveAndFlush}, and an arm
 * that must survive a failed update declares the unit unusable through {@link #markRollbackOnly()}.
 *
 * <h2>Layering and audit</h2>
 *
 * <p>It sits in the repository layer beside the repositories it complements, depends on nothing above it,
 * and holds no state beyond the transaction-bound entity-manager proxy the container supplies. It composes
 * no statement text, so it adds nothing to the raw-SQL count; it resolves no name at runtime and reads no
 * annotation, so it adds nothing to the reflection count. Both counts remain zero.
 *
 * <h2>Provenance</h2>
 *
 * <p>Legacy estate read at checkout {@code 7756d895ffeb65f7ea72aaa609e356d9899afcec}, upstream release
 * stamp {@code CardDemo_v1.0-15-g27d6c6f-68} dated 2022-07-19. The verbs reproduced here are the
 * {@code WRITE}, {@code REWRITE} and {@code DELETE} of the estate's file sections; no legacy source text
 * is reproduced.
 */
@Repository
public class RecordWriter {

    /** Diagnostics for the one arm that reports rather than raises. */
    private static final Logger LOG = LoggerFactory.getLogger(RecordWriter.class);

    /**
     * The complete ANSI/ISO SQL state that means the write was refused because the key was already
     * present.
     *
     * <p>It is the <strong>whole five characters</strong> and not the two-character class, and that is
     * load-bearing. Class {@code 23} is <em>integrity constraint violation</em>, which is a family rather
     * than a condition: PostgreSQL reports {@code 23505} for a unique or primary-key violation, but also
     * {@code 23502} when a column that may not be null is null, {@code 23503} when a foreign key names a
     * row that does not exist, {@code 23514} when a check constraint refuses the value and {@code 23001}
     * for a restrict violation. Only the first is the key already being present. Reading the class alone
     * told every one of them apart from none of them, so an operator who typed a name the store refuses,
     * or a record whose card number names no card, was told the identifier they had chosen was already
     * taken - which was both untrue and unactionable, because no other identifier could clear it. Each of
     * those refusals has its own arm in the source: the write member's catch-all, which was being bypassed.
     */
    private static final String SQLSTATE_UNIQUE_VIOLATION = "23505";

    /**
     * The transaction-bound entity manager.
     *
     * <p>Created through the framework's shared-manager factory, which is what a
     * {@code @PersistenceContext} field would have produced: a thread-safe proxy that resolves, on every
     * call, to the entity manager bound to the unit of work currently in progress. Taking the factory
     * through the constructor keeps this class injectable the same way as every other collaborator in the
     * module and keeps it constructible in a test without a container.
     */
    private final EntityManager entityManager;

    /**
     * @param entityManagerFactory the container's entity-manager factory; must not be {@code null}
     * @throws NullPointerException if {@code entityManagerFactory} is {@code null}
     */
    public RecordWriter(final EntityManagerFactory entityManagerFactory) {
        Objects.requireNonNull(entityManagerFactory, "entityManagerFactory must not be null");
        this.entityManager =
                SharedEntityManagerCreator.createSharedEntityManager(entityManagerFactory);
    }

    /**
     * Inserts one record inside the caller's unit of work and issues the statement immediately.
     *
     * <p>The legacy {@code WRITE} verb: a create, never an update. A key that is already present is
     * refused by the store rather than overwritten, and the refusal surfaces here rather than at commit.
     *
     * @param  <T>    the record type
     * @param  record the record to insert; must not be {@code null}
     * @return the record, now managed by the caller's unit of work
     * @throws NullPointerException if {@code record} is {@code null}
     * @throws org.springframework.dao.DataIntegrityViolationException if the key is already present
     */
    @Transactional(propagation = Propagation.MANDATORY)
    public <T> T insert(final T record) {
        Objects.requireNonNull(record, "record must not be null");
        this.entityManager.persist(record);
        this.entityManager.flush();
        return record;
    }

    /**
     * Inserts every record of a group in the order given, then issues the statements once.
     *
     * <p>One flush for the group rather than one per record, because a group is how the batch tier hands
     * work over and a per-record flush would defeat the driver's own statement batching. Ordering is the
     * caller's: the records are presented in the sequence supplied, which for the combine job is the
     * sorted sequence its ordering step produced. An empty group does nothing at all, not even a flush.
     *
     * @param  <T>     the record type
     * @param  records the records to insert, in order; must not be {@code null} and must hold no
     *                 {@code null}
     * @throws NullPointerException if {@code records} or any element is {@code null}
     * @throws org.springframework.dao.DataIntegrityViolationException if any key is already present
     */
    @Transactional(propagation = Propagation.MANDATORY)
    public <T> void insertAll(final Collection<? extends T> records) {
        Objects.requireNonNull(records, "records must not be null");
        if (records.isEmpty()) {
            return;
        }
        for (final T record : records) {
            Objects.requireNonNull(record, "records must not hold a null record");
            this.entityManager.persist(record);
        }
        this.entityManager.flush();
    }

    /**
     * Inserts one record in a unit of work of its own, so that its outcome is independent of the
     * caller's.
     *
     * <p>For the online create-only writes, whose legacy counterpart is an immediately durable write over
     * a file defined {@code RECOVERY(NONE)}. A success is committed before this method returns; a failure
     * rolls back this insert alone and leaves the caller's unit of work untouched and usable, which is
     * what lets the calling paragraph report the failure on the screen and carry on exactly as the source
     * does.
     *
     * <p>Only ever hand this a record the caller's unit of work has never read. A record read elsewhere is
     * managed elsewhere, and writing it here would leave that other unit of work holding a dirty copy to
     * write again.
     *
     * @param  <T>    the record type
     * @param  record the newly built record to insert; must not be {@code null}
     * @return the record as inserted, detached now that its own unit of work has closed
     * @throws NullPointerException if {@code record} is {@code null}
     * @throws org.springframework.dao.DataIntegrityViolationException if the key is already present
     */
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public <T> T insertIndependently(final T record) {
        Objects.requireNonNull(record, "record must not be null");
        this.entityManager.persist(record);
        this.entityManager.flush();
        return record;
    }

    /**
     * Issues every statement the caller's unit of work has enqueued, without writing anything itself.
     *
     * <p>The write-point flush for a caller whose repository publishes none - the credential repository
     * deliberately exposes a read surface and two write verbs and nothing else - so that a removal's
     * failure arm can act on the failure where the legacy {@code DELETE} acted on it.
     *
     * @throws org.springframework.dao.DataAccessException if the enqueued statements fail
     */
    @Transactional(propagation = Propagation.MANDATORY)
    public void flush() {
        this.entityManager.flush();
    }

    /**
     * Declares the unit of work in progress unusable, so that no commit is attempted for it.
     *
     * <p>Needed on exactly one shape of arm: one where a write has already failed and the legacy program
     * nevertheless reports on the screen and completes the turn. The legacy can do that because its failed
     * write left the file untouched and there was no unit of work to reconcile. Here the failed flush has
     * already invalidated the unit of work, so returning normally would have the boundary attempt a commit
     * that cannot succeed, and the operator would receive a transaction failure in place of the message
     * the source specifies. Declaring the rollback makes the boundary roll back silently and deliver the
     * composed screen - the same observable outcome as the legacy, by the only route that reaches it.
     *
     * <p>Guarded, because a caller may exercise such an arm with no unit of work at all - a unit test does
     * exactly that - and the absence of one is not a fault in this method.
     */
    public void markRollbackOnly() {
        try {
            TransactionAspectSupport.currentTransactionStatus().setRollbackOnly();
        } catch (final NoTransactionException notTransactional) {
            LOG.debug("no unit of work is in progress, so the rollback is recorded without being"
                    + " issued: type={}", notTransactional.getClass().getSimpleName());
        }
    }

    /**
     * Reports whether a failure raised by one of the insert primitives is the refused-key condition that
     * the legacy members' duplicate response arms handle.
     *
     * <p>It lives here because it is the counterpart of the insert: three of the online members have a
     * duplicate arm the source spells out - the transaction-add member folds the two duplicate responses
     * into one arm, and the bill-payment and user-add members do the same - and every one of them needs
     * exactly this classification of exactly this writer's failures. One definition means the three arms
     * cannot drift apart.
     *
     * <h2>The rule, in one sentence</h2>
     *
     * <p>When the store reported an SQL state, that state alone decides, and only the complete state
     * {@value #SQLSTATE_UNIQUE_VIOLATION} is the refused key; when the store reported no state anywhere in
     * the failure, a type that means <em>duplicate</em> and nothing else decides. Nothing here reads a
     * message, a vendor error number or a constraint name, so the classification holds whatever locale a
     * message renders in.
     *
     * <h2>Why the state has to be complete rather than its class</h2>
     *
     * <p>Reading the two-character class {@code 23} accepted every <em>integrity constraint violation</em>
     * as a refused key, and that family is far wider than the condition the duplicate arms handle - see
     * {@link #SQLSTATE_UNIQUE_VIOLATION} for the five states PostgreSQL actually reports inside it. A
     * not-null, foreign-key or check refusal reached the duplicate arm and the operator was told the
     * identifier was already taken; retrying under another identifier could not clear it, because the
     * identifier was never the problem. Each of those refusals has its own arm in the source - the write
     * paragraph's catch-all - and narrowing the state to the complete unique-violation code is what routes
     * it there. Class {@code 22}, <em>data exception</em>, is excluded by the same rule rather than by a
     * second one.
     *
     * <h2>Why the framework's translated type cannot decide this on its own</h2>
     *
     * <p>{@code DataIntegrityViolationException} is the framework's type for the whole integrity family and
     * is raised for a foreign-key, not-null or check refusal exactly as readily as for a duplicate; only
     * its {@code DuplicateKeyException} subtype means <em>this key is already present</em>. The broad type
     * is therefore no longer consulted at all, and the two types that are consulted -
     * {@code DuplicateKeyException} and the provider's {@code EntityExistsException} - each mean the
     * refused key and nothing else. That fallback is reached only when the whole failure carries no SQL
     * state, which is the one situation in which the store said nothing that could demote it.
     *
     * <h2>Why the whole failure is searched, in both directions</h2>
     *
     * <p>A driver exception reports two chains, not one. {@link Throwable#getCause()} is the wrapping
     * chain the framework builds as it translates; {@link SQLException#getNextException()} is the chain the
     * driver itself builds, and PostgreSQL uses it to carry the refusal that a batch or a multi-statement
     * flush actually met. Following only the cause chain therefore reached a wrapper whose own state was
     * {@code null} and stopped, missing the {@value #SQLSTATE_UNIQUE_VIOLATION} hanging off it. Both chains
     * are walked, breadth first, and every visited failure is remembered by identity so a chain that points
     * back at itself terminates instead of looping.
     *
     * @param  failure the failure an insert raised; may be {@code null}, which is not a duplicate
     * @return {@code true} when the key was already present
     */
    public static boolean isDuplicateKey(final Throwable failure) {
        return switch (storeVerdictOn(failure)) {
            case REFUSED_KEY -> true;
            case OTHER_REFUSAL -> false;
            case SILENT -> declaresDuplicateByType(failure);
        };
    }

    /**
     * What the store itself said about the failure, read from every SQL state the failure carries.
     *
     * @param  failure the failure an insert raised; may be {@code null}
     * @return the refused-key verdict when any reported state is the unique violation, the other-refusal
     *         verdict when a state was reported and none of them was, and the silent verdict when the
     *         failure carries no SQL state at all
     */
    private static StoreVerdict storeVerdictOn(final Throwable failure) {
        StoreVerdict verdict = StoreVerdict.SILENT;
        for (final Throwable reported : failureChainOf(failure)) {
            if (!(reported instanceof SQLException driverFailure)) {
                continue;
            }
            final String state = driverFailure.getSQLState();
            if (SQLSTATE_UNIQUE_VIOLATION.equals(state)) {
                return StoreVerdict.REFUSED_KEY;
            }
            if (state != null) {
                verdict = StoreVerdict.OTHER_REFUSAL;
            }
        }
        return verdict;
    }

    /**
     * Reports whether the failure is one of the two types that mean the refused key and nothing else.
     *
     * <p>Consulted only when the store reported no SQL state anywhere in the failure. The broad translated
     * integrity type is deliberately absent: it is raised for every member of the integrity family.
     *
     * @param  failure the failure an insert raised; may be {@code null}
     * @return {@code true} when a duplicate-specific type appears anywhere in the failure
     */
    private static boolean declaresDuplicateByType(final Throwable failure) {
        for (final Throwable candidate : failureChainOf(failure)) {
            if (candidate instanceof EntityExistsException
                    || candidate instanceof DuplicateKeyException) {
                return true;
            }
        }
        return false;
    }

    /**
     * Every failure reachable from the one given, over both chains a driver exception publishes.
     *
     * <p>Breadth first over {@link Throwable#getCause()} and {@link SQLException#getNextException()}, with
     * every failure remembered by identity, so a self-referencing or mutually-referencing chain is visited
     * once and the traversal terminates. A {@code null} failure yields nothing.
     *
     * @param  failure the failure to walk; may be {@code null}
     * @return the failures reachable from it, in visit order, never {@code null}
     */
    private static List<Throwable> failureChainOf(final Throwable failure) {
        final List<Throwable> visited = new ArrayList<>();
        final Set<Throwable> seen = Collections.newSetFromMap(new IdentityHashMap<>());
        final Deque<Throwable> pending = new ArrayDeque<>();
        enqueue(pending, failure);
        while (!pending.isEmpty()) {
            final Throwable candidate = pending.removeFirst();
            if (!seen.add(candidate)) {
                continue;
            }
            visited.add(candidate);
            if (candidate instanceof SQLException driverFailure) {
                enqueue(pending, driverFailure.getNextException());
            }
            enqueue(pending, candidate.getCause());
        }
        return visited;
    }

    /**
     * Adds a failure to the traversal queue when there is one to add.
     *
     * @param pending the queue; must not be {@code null}
     * @param failure the failure to enqueue; may be {@code null}, which enqueues nothing
     */
    private static void enqueue(final Deque<Throwable> pending, final Throwable failure) {
        if (failure != null) {
            pending.addLast(failure);
        }
    }

    /** What the store's own report of a refused write says about the condition that caused it. */
    private enum StoreVerdict {

        /** A reported SQL state is the complete unique violation: the key was already present. */
        REFUSED_KEY,

        /** A state was reported and none of them was the unique violation. */
        OTHER_REFUSAL,

        /** The failure carries no SQL state at all, so the store said nothing about it. */
        SILENT
    }
}
