/*
 * Copyright Amazon.com, Inc. or its affiliates.
 * All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific
 * language governing permissions and limitations under the License
 */
package com.carddemo.repository;

import jakarta.persistence.EntityExistsException;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.Collection;
import java.util.Objects;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.orm.jpa.SharedEntityManagerCreator;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.NoTransactionException;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.interceptor.TransactionAspectSupport;

/**
 * The module's write-point primitives: an insert that is an insert, and a flush that happens where the
 * legacy verb happens.
 *
 * <h2>Why a create needs its own verb</h2>
 *
 * <p>Every record in this estate carries a natural business key that the program assigns before the write
 * - an eleven-digit account identifier, a sixteen-character card number or transaction identifier, an
 * eight-character user identifier. None is generated by the store, so a freshly built entity never has a
 * {@code null} identifier, and that is what decides how a repository's {@code save} behaves: Spring Data
 * asks the entity whether it is new, the answer for an assigned non-{@code null} key without a version
 * attribute is <em>no</em>, and {@code save} therefore resolves to a merge. A merge whose row already
 * exists loads that row and updates it.
 *
 * <p>The consequence is precise and severe. Every legacy {@code WRITE} in the estate is a create whose
 * duplicate-key response the program handles explicitly: the transaction-add member reports
 * {@code Tran ID already exist...}, the bill-payment member reports the same, the user-add member reports
 * {@code User ID already exist...}, and the batch posting member abends. Routed through a merge, none of
 * those arms is reachable, and a duplicate key silently becomes a last-write-wins overwrite of somebody
 * else's record. {@link #insert(Object)} and {@link #insertIndependently(Object)} issue a real insert, so
 * a duplicate key is refused by the store and the arm the legacy specifies is the arm that runs.
 *
 * <h2>Why a flush belongs at the write point</h2>
 *
 * <p>A repository {@code save} enqueues work; the statement reaches the database when the persistence
 * context is flushed, which by default is at commit. A {@code catch} around the save therefore never sees
 * the failure it was written to handle - the failure arrives after the method, after its caller and after
 * every screen the turn composed, at a point where no legacy arm exists to receive it. Flushing inside the
 * write primitive puts the failure back where the legacy verb put it, which is the only place the legacy's
 * own response arms can act on it.
 *
 * <h2>The two propagations, and why the choice is not stylistic</h2>
 *
 * <p>{@link #insert(Object)}, {@link #insertAll(Collection)} and {@link #flush()} require the caller's
 * unit of work and join it. That is right for the batch tier: a legacy batch program abends on a failed
 * write and the step is re-run from its last commit point, so a record's writes must succeed or fail
 * together with the record's own boundary. Committing a posted transaction independently of the chunk that
 * produced it would post it twice on the next restart.
 *
 * <p>{@link #insertIndependently(Object)} opens its own unit of work. That is right for the online tier,
 * and for a reason the resource definitions state rather than a convenience: every application file in
 * {@code app/csd/CARDDEMO.CSD} is defined {@code RECOVERY(NONE)} with {@code JOURNAL(NO)}, so a legacy
 * record write is immediately durable and no unit of work backs it out. An online member that reports a
 * failed write on the screen and carries on - which is what the bill-payment member does at its line 233,
 * where the account rewrite at line 235 is reached whether or not the write succeeded - cannot be
 * reproduced inside a single unit of work, because a failed flush leaves that unit unusable for anything
 * that follows. An independent boundary reproduces both halves: the write is durable on its own, and its
 * failure is contained.
 *
 * <p><strong>Independent boundaries are offered for creates only, deliberately.</strong> An update reads
 * its row first, and that row is then managed by the reading unit of work. Writing it through a second,
 * independent unit of work would leave the first one still holding a dirty copy, which it would write
 * again at its own commit - a second update carrying a stale version. Updates therefore stay in the
 * caller's unit of work and flush there, through the repository's own {@code saveAndFlush}, and an arm
 * that must survive a failed update declares the unit unusable through {@link #markRollbackOnly()}.
 *
 * <h2>Layering and audit</h2>
 *
 * <p>It sits in the repository layer beside the repositories it complements, depends on nothing above it,
 * and holds no state beyond the transaction-bound entity-manager proxy the container supplies. It composes
 * no statement text, so it adds nothing to the raw-SQL count; it resolves no name at runtime and reads no
 * annotation, so it adds nothing to the reflection count. Both counts remain zero.
 *
 * <h2>Provenance</h2>
 *
 * <p>Legacy estate read at checkout {@code 7756d895ffeb65f7ea72aaa609e356d9899afcec}, upstream release
 * stamp {@code CardDemo_v1.0-15-g27d6c6f-68} dated 2022-07-19. The verbs reproduced here are the
 * {@code WRITE}, {@code REWRITE} and {@code DELETE} of the estate's file sections; no legacy source text
 * is reproduced.
 */
@Repository
public class RecordWriter {

    /** Diagnostics for the one arm that reports rather than raises. */
    private static final Logger LOG = LoggerFactory.getLogger(RecordWriter.class);

    /**
     * The ANSI/ISO SQL state class that means a constraint refused the write.
     *
     * <p>The two-character class is the first half of the five-character state every JDBC driver publishes;
     * class {@code 23} is <em>integrity constraint violation</em>, which for an insert is the key already
     * being present. It is deliberately the class rather than a complete state, because the four subclasses
     * a store may report - unique, primary key, foreign key, check - are all the same answer to the only
     * question asked here, and pinning a full state would tie this to one store's choice among them.
     */
    private static final String SQLSTATE_CLASS_INTEGRITY_CONSTRAINT = "23";

    /** The number of leading characters of an SQL state that carry its class. */
    private static final int SQLSTATE_CLASS_LENGTH = 2;

    /**
     * The transaction-bound entity manager.
     *
     * <p>Created through the framework's shared-manager factory, which is what a
     * {@code @PersistenceContext} field would have produced: a thread-safe proxy that resolves, on every
     * call, to the entity manager bound to the unit of work currently in progress. Taking the factory
     * through the constructor keeps this class injectable the same way as every other collaborator in the
     * module and keeps it constructible in a test without a container.
     */
    private final EntityManager entityManager;

    /**
     * @param entityManagerFactory the container's entity-manager factory; must not be {@code null}
     * @throws NullPointerException if {@code entityManagerFactory} is {@code null}
     */
    public RecordWriter(final EntityManagerFactory entityManagerFactory) {
        Objects.requireNonNull(entityManagerFactory, "entityManagerFactory must not be null");
        this.entityManager =
                SharedEntityManagerCreator.createSharedEntityManager(entityManagerFactory);
    }

    /**
     * Inserts one record inside the caller's unit of work and issues the statement immediately.
     *
     * <p>The legacy {@code WRITE} verb: a create, never an update. A key that is already present is
     * refused by the store rather than overwritten, and the refusal surfaces here rather than at commit.
     *
     * @param  <T>    the record type
     * @param  record the record to insert; must not be {@code null}
     * @return the record, now managed by the caller's unit of work
     * @throws NullPointerException if {@code record} is {@code null}
     * @throws org.springframework.dao.DataIntegrityViolationException if the key is already present
     */
    @Transactional(propagation = Propagation.MANDATORY)
    public <T> T insert(final T record) {
        Objects.requireNonNull(record, "record must not be null");
        this.entityManager.persist(record);
        this.entityManager.flush();
        return record;
    }

    /**
     * Inserts every record of a group in the order given, then issues the statements once.
     *
     * <p>One flush for the group rather than one per record, because a group is how the batch tier hands
     * work over and a per-record flush would defeat the driver's own statement batching. Ordering is the
     * caller's: the records are presented in the sequence supplied, which for the combine job is the
     * sorted sequence its ordering step produced. An empty group does nothing at all, not even a flush.
     *
     * @param  <T>     the record type
     * @param  records the records to insert, in order; must not be {@code null} and must hold no
     *                 {@code null}
     * @throws NullPointerException if {@code records} or any element is {@code null}
     * @throws org.springframework.dao.DataIntegrityViolationException if any key is already present
     */
    @Transactional(propagation = Propagation.MANDATORY)
    public <T> void insertAll(final Collection<? extends T> records) {
        Objects.requireNonNull(records, "records must not be null");
        if (records.isEmpty()) {
            return;
        }
        for (final T record : records) {
            Objects.requireNonNull(record, "records must not hold a null record");
            this.entityManager.persist(record);
        }
        this.entityManager.flush();
    }

    /**
     * Inserts one record in a unit of work of its own, so that its outcome is independent of the
     * caller's.
     *
     * <p>For the online create-only writes, whose legacy counterpart is an immediately durable write over
     * a file defined {@code RECOVERY(NONE)}. A success is committed before this method returns; a failure
     * rolls back this insert alone and leaves the caller's unit of work untouched and usable, which is
     * what lets the calling paragraph report the failure on the screen and carry on exactly as the source
     * does.
     *
     * <p>Only ever hand this a record the caller's unit of work has never read. A record read elsewhere is
     * managed elsewhere, and writing it here would leave that other unit of work holding a dirty copy to
     * write again.
     *
     * @param  <T>    the record type
     * @param  record the newly built record to insert; must not be {@code null}
     * @return the record as inserted, detached now that its own unit of work has closed
     * @throws NullPointerException if {@code record} is {@code null}
     * @throws org.springframework.dao.DataIntegrityViolationException if the key is already present
     */
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public <T> T insertIndependently(final T record) {
        Objects.requireNonNull(record, "record must not be null");
        this.entityManager.persist(record);
        this.entityManager.flush();
        return record;
    }

    /**
     * Issues every statement the caller's unit of work has enqueued, without writing anything itself.
     *
     * <p>The write-point flush for a caller whose repository publishes none - the credential repository
     * deliberately exposes a read surface and two write verbs and nothing else - so that a removal's
     * failure arm can act on the failure where the legacy {@code DELETE} acted on it.
     *
     * @throws org.springframework.dao.DataAccessException if the enqueued statements fail
     */
    @Transactional(propagation = Propagation.MANDATORY)
    public void flush() {
        this.entityManager.flush();
    }

    /**
     * Declares the unit of work in progress unusable, so that no commit is attempted for it.
     *
     * <p>Needed on exactly one shape of arm: one where a write has already failed and the legacy program
     * nevertheless reports on the screen and completes the turn. The legacy can do that because its failed
     * write left the file untouched and there was no unit of work to reconcile. Here the failed flush has
     * already invalidated the unit of work, so returning normally would have the boundary attempt a commit
     * that cannot succeed, and the operator would receive a transaction failure in place of the message
     * the source specifies. Declaring the rollback makes the boundary roll back silently and deliver the
     * composed screen - the same observable outcome as the legacy, by the only route that reaches it.
     *
     * <p>Guarded, because a caller may exercise such an arm with no unit of work at all - a unit test does
     * exactly that - and the absence of one is not a fault in this method.
     */
    public void markRollbackOnly() {
        try {
            TransactionAspectSupport.currentTransactionStatus().setRollbackOnly();
        } catch (final NoTransactionException notTransactional) {
            LOG.debug("no unit of work is in progress, so the rollback is recorded without being"
                    + " issued: type={}", notTransactional.getClass().getSimpleName());
        }
    }

    /**
     * Reports whether a failure raised by one of the insert primitives is the refused-key condition that
     * the legacy members' duplicate response arms handle.
     *
     * <p>It lives here because it is the counterpart of the insert: three of the online members have a
     * duplicate arm the source spells out - the transaction-add member folds the two duplicate responses
     * into one arm, and the bill-payment and user-add members do the same - and every one of them needs
     * exactly this classification of exactly this writer's failures. One definition means the three arms
     * cannot drift apart.
     *
     * <p>The classification reads the store's own report of the failure where one was made, and otherwise
     * matches on the persistence provider's duplicate-entity type and the framework's two translated
     * integrity types. It never reads a message and never reads a vendor error number, so it holds whatever
     * database is configured and whatever locale a message is rendered in.
     *
     * <h2>Why the framework's translated type cannot decide this on its own</h2>
     *
     * <p>{@code DataIntegrityViolationException} is broader than the condition the duplicate arms handle.
     * The framework's state-based translation groups several SQL state classes onto that one type, and
     * only one of them is a refused key: class {@code 23} is <em>integrity constraint violation</em>,
     * while class {@code 22} is <em>data exception</em> - a value the column cannot hold at all. Read as a
     * duplicate, a class {@code 22} failure told an operator that the identifier they had chosen was
     * already taken when in fact it was free and their name field held a character the store refuses, and
     * no amount of retrying under a different identifier could clear it. The user-add member's own
     * catch-all write-failure arm is the arm the source specifies for that failure, and it was being
     * bypassed.
     *
     * <p>So when the store has reported for itself, its report decides and the translated type is not
     * consulted: a JDBC integrity-constraint type, or an SQL state in class {@code 23}, is the refused
     * key; any other state class is not. This keeps the method's own rule intact - an SQL state is the
     * ANSI/ISO standard code every driver publishes in the same five characters, not a vendor error
     * number and not a message, so nothing here depends on which database is configured or on the
     * locale a message renders in. The provider's exception hierarchy is deliberately not consulted
     * either, which keeps this class free of any dependency on which JPA provider is in use.
     *
     * <p>When no state is available the typed test stands as before, because a failure that carries no
     * report from the store carries no evidence to demote it: a provider that raises the duplicate-entity
     * type from its own persistence context, and a translated integrity failure built without an
     * underlying driver exception, both still classify as the refused key.
     *
     * @param  failure the failure an insert raised; may be {@code null}, which is not a duplicate
     * @return {@code true} when the key was already present
     */
    public static boolean isDuplicateKey(final Throwable failure) {
        final SQLException reported = decisiveStoreReport(failure);
        if (reported != null) {
            return reportsRefusedKey(reported);
        }
        for (Throwable candidate = failure; candidate != null; candidate = candidate.getCause()) {
            if (candidate instanceof EntityExistsException
                    || candidate instanceof DuplicateKeyException
                    || candidate instanceof DataIntegrityViolationException) {
                return true;
            }
            if (candidate.getCause() == candidate) {
                return false;
            }
        }
        return false;
    }

    /**
     * Finds the store's own report of the failure, when it made one this method can act on.
     *
     * <p>A report is only decisive if it identifies the condition: either it is the JDBC type reserved for
     * an integrity-constraint violation, or it carries an SQL state long enough to read a class from. A
     * driver exception with no state says no more than the translated type above it already said, so it is
     * passed over and the typed test is left to decide.
     *
     * @param  failure the failure an insert raised; may be {@code null}
     * @return the first driver exception in the chain that identifies the condition, or {@code null}
     */
    private static SQLException decisiveStoreReport(final Throwable failure) {
        for (Throwable candidate = failure; candidate != null; candidate = candidate.getCause()) {
            if (candidate instanceof SQLException reported
                    && (reported instanceof SQLIntegrityConstraintViolationException
                            || hasReadableState(reported))) {
                return reported;
            }
            if (candidate.getCause() == candidate) {
                return null;
            }
        }
        return null;
    }

    /**
     * Reports whether a driver exception carries an SQL state a class can be read from.
     *
     * @param  reported the driver exception; must not be {@code null}
     * @return {@code true} when a state class is readable
     */
    private static boolean hasReadableState(final SQLException reported) {
        final String state = reported.getSQLState();
        return state != null && state.length() >= SQLSTATE_CLASS_LENGTH;
    }

    /**
     * Reports whether the store's own report is the refused-key condition.
     *
     * @param  reported the driver exception; must not be {@code null}
     * @return {@code true} when the store refused the write because the key was already present
     */
    private static boolean reportsRefusedKey(final SQLException reported) {
        if (reported instanceof SQLIntegrityConstraintViolationException) {
            return true;
        }
        final String state = reported.getSQLState();
        return state != null && state.startsWith(SQLSTATE_CLASS_INTEGRITY_CONSTRAINT);
    }
}
